make importing translations optional

diff --git a/Makefile.po.inc b/Makefile.po.inc
--- a/Makefile.po.inc
+++ b/Makefile.po.inc
@@ -33,16 +33,19 @@ clean:
 	rm -f $(DOMAIN).pot *.mo *.po intltool-extract
 
 prepare:
-	[ -d $(PO_DIR) ]
-	for i in $(LANGS); \
-	do \
-		if [ -e $(PO_DIR)/frugalwareutils/$$i/$(DOMAIN).po ]; then \
-			cp $(PO_DIR)/frugalwareutils/$$i/$(DOMAIN).po $$i.po; \
-			if ! msgfmt -c --statistics -o $$i.gmo $$i.po; then \
-				echo "ERROR: $(DOMAIN)/$$i.po would break your build!"; \
-				exit 1; \
+	@if [ -d $(PO_DIR) ]; then \
+		for i in $(LANGS); \
+		do \
+			if [ -e $(PO_DIR)/frugalwareutils/$$i/$(DOMAIN).po ]; then \
+				cp $(PO_DIR)/frugalwareutils/$$i/$(DOMAIN).po $$i.po; \
+				if ! msgfmt -c --statistics -o $$i.gmo $$i.po; then \
+					echo "ERROR: $(DOMAIN)/$$i.po would break your build!"; \
+					exit 1; \
+				fi; \
 			fi; \
-		fi; \
-	done
+		done; \
+	else \
+		echo "WARNING: $(PO_DIR) does not exists, skipping translations for $(DOMAIN)."; \
+	fi
 
 # vim: ft=make
